zachetka_news/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'page#home'
    get '/home' => 'page#home', :as => 'home'
    get '/account' => 'page#account', :as => 'account'
    get '/update_pref' => 'user#update_preferences', :as => 'update_pref'
    resources :news_items
  end
end

zachetka_news/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

zachetka_news/app/models/news_item.rb
# frozen_string_literal: true

class NewsItem < ApplicationRecord
  belongs_to :news_type
end

zachetka_news/app/models/news_type.rb
# frozen_string_literal: true

class NewsType < ApplicationRecord
  has_many :news_items

  DEFAULT_TYPE = 'general'

  class << self
    def default_type
      find_by(type_name: DEFAULT_TYPE)
    end
  end
end

zachetka_news/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :news_items

  after_initialize :default_values

  def username
    email.match(/[^@]+/).to_s
  end

  private

  def default_values
    self.is_admin = false
  end
end

zachetka_news/app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  def admin_page; end
end

zachetka_news/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :language_set

  def language_set
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

zachetka_news/app/controllers/news_items_controller.rb
# frozen_string_literal: true

class NewsItemsController < ApplicationController
  before_action :set_news_item, only: %i[show edit update destroy]
  before_action :check_admin

  NEWS_TYPE_PARAM_NAME = 'news_type'
  NEWS_ITEM_PARAM_NAME = 'news_item'

  def index
    @news_items = NewsItem.all
  end

  def show
    redirect_to news_items_path
  end

  def new
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    @news_item = NewsItem.new(news_item_params.to_h.reject { |k| k.eql?(NEWS_TYPE_PARAM_NAME) })
    @news_item.news_type = NewsType.find_by(type_name: params[NEWS_ITEM_PARAM_NAME][NEWS_TYPE_PARAM_NAME])

    if @news_item.save
      redirect_to @news_item, notice: 'News successfully created'
    else
      redirect_to new_news_item_path, notice: 'Parameters cant be empty'
    end
  end

  def update
    puts "TEST #{news_item_params}"
    if @news_item.update(news_item_params)
      redirect_to @news_item, notice: 'News successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @news_item.destroy
    redirect_to news_items_url, notice: 'News successfully deleted'
  end

  private

  def check_item_params(params)
    params.values.all?(&:present?)
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  def news_item_params
    params.fetch(:news_item, {}).permit(:title, :subtitle, :source_url, :news_type)
  end

  def check_admin
    redirect_to home_path unless current_user&.is_admin
  end
end

zachetka_news/app/controllers/page_controller.rb
# frozen_string_literal: true

class PageController < ApplicationController
  before_action :authenticate_user!, only: [:account]

  def home
    @news = NewsApiHelper.call(country: I18n.locale, category: user_pref).res
    @admin_news = NewsItem.where(news_type: NewsType.find_by(type_name: user_pref))
  end

  def account; end

  private

  def user_pref
    if current_user && !current_user.preference.nil?
      current_user.preference
    else
      NewsType.default_type&.type_name
    end
  end
end

zachetka_news/app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  def update_preferences
    User.find_by(email: current_user.email).update(preference: params[:pref])
    respond_to { |format| format.js }
  end
end

zachetka_news/app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

zachetka_news/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_preferences
    [
      [t('account_page.news_type.business'), 'business'],
      [t('account_page.news_type.health'), 'health'],
      [t('account_page.news_type.entertainment'), 'entertainment'],
      [t('account_page.news_type.general'), 'general'],
      [t('account_page.news_type.science'), 'science'],
      [t('account_page.news_type.sports'), 'sports'],
      [t('account_page.news_type.technology'), 'technology']
    ]
  end
end

zachetka_news/app/helpers/news_items_helper.rb
# frozen_string_literal: true

module NewsItemsHelper
end

zachetka_news/app/helpers/page_helper.rb
# frozen_string_literal: true

module PageHelper
  def usd_rate
    ExchangeRate.call(val: 1, from: 'USD', to: 'RUB').res * 100
  end

  def eur_rate
    ExchangeRate.call(val: 1, from: 'EUR', to: 'RUB').res * 100
  end
end

zachetka_news/app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

zachetka_news/app/views/layouts/_devise_notifications.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

zachetka_news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Новости</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar news-header" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <div class="logo">
              <div class="after-name">WorldNews</div>
            </div>
          </a>
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <div class="navbar-item">
              <div class="buttons">
                <%= link_to t('main_page.home_link'), home_path, class: "button is-link is-rounded" %>
                <%= link_to t('main_page.setting'), account_path, class: "button is-link is-rounded" %>
                <% if current_user&.is_admin %>
                  <%= link_to t('main_page.admin_panel'), news_items_path, class: "button is-success is-rounded" %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <button class="button is-rounded is-small"><%= link_to 'EN', locale: :us %></button>
                <button class="button is-rounded is-small"><%= link_to 'RU', locale: :ru %></button>
              </div>
            </div>
            <div class="navbar-item">
              <div class="buttons">
                <% if current_user %>
                  <%= link_to t('main_page.signout'), destroy_user_session_url, method: :delete, class: "button is-danger is-rounded" %>
                <% else %>
                  <%= link_to t('main_page.signup'), new_user_registration_path, class: "button is-info is-rounded" %>
                  <%= link_to t('main_page.signin'), new_user_session_path, class: "button is-success is-rounded" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

zachetka_news/app/views/news_items/_form.html.erb
<%= form_with(model: news_item, local: true) do |form| %>
  <div class="field">
    <label class="label"><%= t('news_items.form_title') %></label>
    <div class="control">
      <%= form.text_field :title, class: 'input', placeholder: "Заголовок" %>
    </div>
  </div>

  <div class="field">
    <label class="label"><%= t('news_items.form_subtitle') %></label>
    <div class="control">
      <%= form.text_area :subtitle, class: 'textarea', placeholder: "Основная часть" %>
    </div>
  </div>

  <div class="field">
    <label class="label"><%= t('news_items.form_source_url') %></label>
    <div class="control">
      <%= form.text_field :source_url, class: 'input', placeholder: "Ссылка на источник" %>
    </div>
  </div>

  <div class="field">
    <label class="label"><%= t('news_items.form_news_type') %></label>
    <div class="select">
      <%= form.select :news_type, options_for_select(user_preferences) %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit t('news_items.form_save'), class: "button is-link" %>
  </div>
<% end %>

zachetka_news/app/views/news_items/edit.html.erb
<div class="container news-content">
  <h1 class="title"><%= t('news_items.form_change_news') %></h1>
  <%= render 'form', news_item: @news_item %>
</div>

zachetka_news/app/views/news_items/index.html.erb
<% unless notice.blank? %>
  <div class="notification is-info">
    <%= notice %>
  </div>
<% end %>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= t('news_items.admin_panel') %>
      </h1>
    </div>
  </div>
</section>
<div class="container news-content">
  <h1 class="title"><%= t('news_items.personal_news') %></h1>
  <%= link_to t('news_items.add_news'), new_news_item_path, class: "button is-link is-rounded" %>
  <% @news_items.each do |news| %>
    <%= link_to news.source_url do %>
      <div class="card news-card">
        <div class="card-content">
          <p class="title">
            <%= news.title %>
          </p>
          <p class="subtitle">
            <%= news.subtitle %>
          </p>
        </div>
        <footer class="card-footer">
          <p class="card-footer-item">
            <span>
              <%= link_to t('main_page.source'), news.source_url, class: "button is-ghost is-rounded" %>
            </span>
          </p>
          <p class="card-footer-item">
            <span>
              <%= link_to t('news_items.edit'), edit_news_item_path(news), class: "button is-warning is-rounded" %>
              <%= link_to t('news_items.delete'), news, method: :delete, data: { confirm: t('news_items.confirm') }, class: "button is-danger is-rounded" %>
            </span>
          </p>
        </footer>
      </div>
    <% end %>
  <% end %>
</div>

zachetka_news/app/views/news_items/new.html.erb
<% unless notice.blank? %>
  <div class="notification is-info">
    <%= notice %>
  </div>
<% end %>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= t('news_items.admin_panel') %>
      </h1>
    </div>
  </div>
</section>

<div class="container news-content">
  <h1 class="title"><%= t('news_items.add_news') %></h1>
  <%= render 'form', news_item: @news_item %>
</div>

zachetka_news/app/views/news_items/show.html.erb
<% unless notice.blank? %>
  <div class="notification is-info">
    <%= notice %>
  </div>
<% end %>

<div class="container news-content">
  <h1 class="title"><%= t('news_items.add_news') %></h1>
  <%= render 'layouts/devise_notifications.html.erb' %>
  <%= render 'form', news_item: @news_item %>
</div>

<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>

zachetka_news/app/views/page/account.html.erb
<div class="container news-content">
  <div class="card">
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-3"><%= current_user.username %></p>
          <% if current_user&.is_admin %>
            <p class="subtitle is-6 has-text-success"><%= t('news_items.admin') %></p>
          <% end %>
          <p class="subtitle is-6"><%= current_user.email %></p>
          <p class="subtitle is-6"><%= t 'account_page.since' %><%= current_user.created_at %></p>
        </div>
      </div>

      <div class="content">
        <div class="title"><%= t 'account_page.preffered_news' %></div>

        <%= form_tag url_for(:action => 'update_preferences', :controller => 'user'), :method => 'get', remote: true do %>
        <div class="select">
          <%= select_tag :pref, options_for_select(user_preferences) %>
        </div>
        <div class="content news-content">
          <%= submit_tag t('account_page.submit'), class: "button is-primary" %>
        </div>
        <% end %>
      </div>
      <p class="help is-success res-info"></p>
    </div>
  </div>
</div>

zachetka_news/app/views/page/home.html.erb
<div class="ticker-wrap">
  <div class="ticker">
    <% @news.take(5).each do |news| %>
      <div class="ticker__item"><%= news.title %></div>
    <% end %>
  </div>
</div>

<div class="container news-content">
  <div class="columns">
    <div class="column">
      <%= render 'layouts/devise_notifications.html.erb' %>
      <% @admin_news.each do |news| %>
        <%= link_to news.source_url do %>
          <div class="card news-card">
            <div class="card-content">
              <p class="title">
                <%= news.title %>
              </p>
              <p class="subtitle">
                <%= news.subtitle %>
              </p>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item">
                <span>
                  <%= link_to t('main_page.source'), news.source_url %>
                </span>
              </p>
            </footer>
          </div>
        <% end %>
      <% end %>
      <% @news.each do |news| %>
        <%= link_to news.url do %>
          <div class="card news-card">
            <div class="card-content">
              <p class="title">
                <%= news.title %>
              </p>
              <p class="subtitle">
                <%= news.description %>
              </p>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item">
                <span>
                  <%= link_to t('main_page.source'), news.url %>
                </span>
              </p>
            </footer>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="column is-one-third">
      <div class="box exchange-rate-box">
        <div class="content">
          <div class="exchange-rate-value"><%= t 'main_page.exch' %></div>
          <div class="exchange-rate-value">$ <%= usd_rate %></div>
          <div class="exchange-rate-value">€ <%= eur_rate %></div>
        </div>
      </div>
    </div>
  </div>
</div>

zachetka_news/app/views/user/update_preferences.js.erb
var appendText = `
  <%= t 'account_page.result_sub' %>
`

$('.res-info').append(appendText)